[[* Note: Do not edit this file! It will be updated in forthcoming versions 
of PivotX, so you will lose your changes. *]]

<form method="post" action="[[ self ]]#message" id="commentform">
<h4>Leave a comment</h4>	
		<label for="piv_name">Name (required)</label>
		<input type="text" name="piv_name" id="piv_name" size="20" class="text-input" value="[[ remember name=name ]]" />
	
		<label for="piv_email">Email (required, will not be published)</label>
		<input name="piv_email" id="piv_email" type="text" size="30" class="text-input" value="[[ remember name=email ]]" />
	
		<label for="piv_url">Website</label>
		<input name="piv_url" id="piv_url" type="text" size="30" class="text-input" value="[[ remember name=url ]]" />
	
		<label for="piv_comment">Comment</label>
		<textarea name="piv_comment" id="piv_comment" cols="30" rows="10">[[ remember name="comment"]]</textarea>
	
	[[ spamquiz ]]
	
	[[ moderate_message ]]
	

		<input type="hidden" name="piv_code" value="[[ $entry.uid ]]" />
		<input type="hidden" name="piv_weblog" value="[[ weblogid ]]" />
		<input type="submit" name="post" value="[[t]]Post Comment[[/t]]" class="submit" /> 
		<input type="submit" name="preview" value="[[t]]Preview Comment[[/t]]" class="submit" />
</form>
